import type { Application, ApplicationStatus, Company } from "./types";

const companies: Company[] = [
  {
    id: 1,
    slug: "google",
    name: "Google",
    desc: "Technology company specializing in Internet-related services",
    logoUrl: "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
    websiteUrl: "https://google.com",
    address: "Mountain View, CA"
  },
  {
    id: 2,
    slug: "microsoft",
    name: "Microsoft",
    desc: "Multinational technology corporation",
    logoUrl: "https://img-prod-cms-rt-microsoft-com.akamaized.net/cms/api/am/imageFileData/RE1Mu3b?ver=5c31",
    websiteUrl: "https://microsoft.com",
    address: "Redmond, WA"
  },
  {
    id: 3,
    slug: "meta",
    name: "Meta",
    desc: "Social technology company",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Meta_Platforms_Inc._logo.svg/512px-Meta_Platforms_Inc._logo.svg.png",
    websiteUrl: "https://meta.com",
    address: "Menlo Park, CA"
  },
  {
    id: 4,
    slug: "amazon",
    name: "Amazon",
    desc: "Technology and e-commerce company",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/603px-Amazon_logo.svg.png",
    websiteUrl: "https://amazon.com",
    address: "Seattle, WA"
  },
  {
    id: 5,
    slug: "apple",
    name: "Apple",
    desc: "Technology company that designs and sells electronics",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/f/fa/Apple_logo_black.svg",
    websiteUrl: "https://apple.com",
    address: "Cupertino, CA"
  },
  {
    id: 6,
    slug: "netflix",
    name: "Netflix",
    desc: "Streaming entertainment service",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/0/08/Netflix_2015_logo.svg",
    websiteUrl: "https://netflix.com",
    address: "Los Gatos, CA"
  },
  {
    id: 7,
    slug: "spotify",
    name: "Spotify",
    desc: "Audio streaming and media services provider",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/1/19/Spotify_logo_without_text.svg",
    websiteUrl: "https://spotify.com",
    address: "Stockholm, Sweden"
  },
  {
    id: 8,
    slug: "stripe",
    name: "Stripe",
    desc: "Financial services and software company",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/b/ba/Stripe_Logo%2C_revised_2016.svg",
    websiteUrl: "https://stripe.com",
    address: "San Francisco, CA"
  },
  {
    id: 9,
    slug: "airbnb",
    name: "Airbnb",
    desc: "Online marketplace for lodging and tourism",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/6/69/Airbnb_Logo_B%C3%A9lo.svg",
    websiteUrl: "https://airbnb.com",
    address: "San Francisco, CA"
  },
  {
    id: 10,
    slug: "uber",
    name: "Uber",
    desc: "Mobility and delivery platform",
    logoUrl: "https://upload.wikimedia.org/wikipedia/commons/c/cc/Uber_logo_2018.png",
    websiteUrl: "https://uber.com",
    address: "San Francisco, CA"
  }
];

export const dummyApplications: Application[] = [
  {
    id: 1,
    companyId: 1,
    userId: "user-1",
    position: "Senior Software Engineer",
    jobUrl: "https://google.com/careers/1",
    jobDescription: "Senior Software Engineer role at Google",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 150000,
    maxSalary: 220000,
    location: "Mountain View, CA",
    remote: "HYBRID",
    listedAt: new Date("2026-01-01"),
    appliedAt: null,
    interviewAt: null,
    offerAt: null,
    rejectedAt: null,
    declinedAt: null,
    signedAt: null,
    status: "LISTED",
    company: companies[0]!
  },
  {
    id: 2,
    companyId: 2,
    userId: "user-1",
    position: "Full Stack Developer",
    jobUrl: "https://microsoft.com/careers/2",
    jobDescription: "Full Stack Developer role at Microsoft",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 140000,
    maxSalary: 200000,
    location: "Redmond, WA",
    remote: "REMOTE",
    listedAt: new Date("2026-01-05"),
    appliedAt: null,
    interviewAt: null,
    offerAt: null,
    rejectedAt: null,
    declinedAt: null,
    signedAt: null,
    status: "LISTED",
    company: companies[1]!
  },
  {
    id: 3,
    companyId: 7,
    userId: "user-1",
    position: "Frontend Engineer",
    jobUrl: "https://spotify.com/careers/3",
    jobDescription: "Frontend Engineer role at Spotify",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 130000,
    maxSalary: 180000,
    location: "Stockholm, Sweden",
    remote: "ONSITE",
    listedAt: new Date("2026-01-10"),
    appliedAt: null,
    interviewAt: null,
    offerAt: null,
    rejectedAt: null,
    declinedAt: null,
    signedAt: null,
    status: "LISTED",
    company: companies[6]!
  },
  {
    id: 4,
    companyId: 3,
    userId: "user-1",
    position: "Product Engineer",
    jobUrl: "https://meta.com/careers/4",
    jobDescription: "Product Engineer role at Meta",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 160000,
    maxSalary: 230000,
    location: "Menlo Park, CA",
    remote: "HYBRID",
    listedAt: new Date("2025-12-15"),
    appliedAt: new Date("2026-01-05"),
    interviewAt: null,
    offerAt: null,
    rejectedAt: null,
    declinedAt: null,
    signedAt: null,
    status: "APPLIED",
    company: companies[2]!
  },
  {
    id: 5,
    companyId: 4,
    userId: "user-1",
    position: "Backend Developer",
    jobUrl: "https://amazon.com/careers/5",
    jobDescription: "Backend Developer role at Amazon",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 145000,
    maxSalary: 210000,
    location: "Seattle, WA",
    remote: "ONSITE",
    listedAt: new Date("2025-12-20"),
    appliedAt: new Date("2026-01-08"),
    interviewAt: null,
    offerAt: null,
    rejectedAt: null,
    declinedAt: null,
    signedAt: null,
    status: "APPLIED",
    company: companies[3]!
  },
  {
    id: 6,
    companyId: 8,
    userId: "user-1",
    position: "Platform Engineer",
    jobUrl: "https://stripe.com/careers/6",
    jobDescription: "Platform Engineer role at Stripe",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 170000,
    maxSalary: 250000,
    location: "San Francisco, CA",
    remote: "REMOTE",
    listedAt: new Date("2025-12-25"),
    appliedAt: new Date("2026-01-10"),
    interviewAt: null,
    offerAt: null,
    rejectedAt: null,
    declinedAt: null,
    signedAt: null,
    status: "APPLIED",
    company: companies[7]!
  },
  {
    id: 7,
    companyId: 10,
    userId: "user-1",
    position: "Software Engineer II",
    jobUrl: "https://uber.com/careers/7",
    jobDescription: "Software Engineer II role at Uber",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 135000,
    maxSalary: 190000,
    location: "San Francisco, CA",
    remote: "HYBRID",
    listedAt: new Date("2025-12-28"),
    appliedAt: new Date("2026-01-12"),
    interviewAt: null,
    offerAt: null,
    rejectedAt: null,
    declinedAt: null,
    signedAt: null,
    status: "APPLIED",
    company: companies[9]!
  },
  {
    id: 8,
    companyId: 5,
    userId: "user-1",
    position: "iOS Developer",
    jobUrl: "https://apple.com/careers/8",
    jobDescription: "iOS Developer role at Apple",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 155000,
    maxSalary: 225000,
    location: "Cupertino, CA",
    remote: "ONSITE",
    listedAt: new Date("2025-12-01"),
    appliedAt: new Date("2025-12-10"),
    interviewAt: new Date("2026-01-15"),
    offerAt: null,
    rejectedAt: null,
    declinedAt: null,
    signedAt: null,
    status: "INTERVIEW",
    company: companies[4]!
  },
  {
    id: 9,
    companyId: 9,
    userId: "user-1",
    position: "Senior Frontend Engineer",
    jobUrl: "https://airbnb.com/careers/9",
    jobDescription: "Senior Frontend Engineer role at Airbnb",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 165000,
    maxSalary: 240000,
    location: "San Francisco, CA",
    remote: "HYBRID",
    listedAt: new Date("2025-12-05"),
    appliedAt: new Date("2025-12-15"),
    interviewAt: new Date("2026-01-20"),
    offerAt: null,
    rejectedAt: null,
    declinedAt: null,
    signedAt: null,
    status: "INTERVIEW",
    company: companies[8]!
  },
  {
    id: 10,
    companyId: 6,
    userId: "user-1",
    position: "Senior Backend Engineer",
    jobUrl: "https://netflix.com/careers/10",
    jobDescription: "Senior Backend Engineer role at Netflix",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 180000,
    maxSalary: 280000,
    location: "Los Gatos, CA",
    remote: "REMOTE",
    listedAt: new Date("2025-11-15"),
    appliedAt: new Date("2025-11-25"),
    interviewAt: new Date("2025-12-15"),
    offerAt: new Date("2026-01-25"),
    rejectedAt: null,
    declinedAt: null,
    signedAt: null,
    status: "OFFER",
    company: companies[5]!
  },
  {
    id: 11,
    companyId: 1,
    userId: "user-1",
    position: "Staff Engineer",
    jobUrl: "https://google.com/careers/11",
    jobDescription: "Staff Engineer role at Google",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 200000,
    maxSalary: 350000,
    location: "Mountain View, CA",
    remote: "HYBRID",
    listedAt: new Date("2025-11-01"),
    appliedAt: new Date("2025-11-10"),
    interviewAt: new Date("2025-12-01"),
    offerAt: null,
    rejectedAt: new Date("2026-01-28"),
    declinedAt: null,
    signedAt: null,
    status: "REJECTED",
    company: companies[0]!
  },
  {
    id: 12,
    companyId: 3,
    userId: "user-1",
    position: "Engineering Manager",
    jobUrl: "https://meta.com/careers/12",
    jobDescription: "Engineering Manager role at Meta",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 220000,
    maxSalary: 320000,
    location: "Menlo Park, CA",
    remote: "ONSITE",
    listedAt: new Date("2025-10-20"),
    appliedAt: new Date("2025-11-01"),
    interviewAt: new Date("2025-12-10"),
    offerAt: null,
    rejectedAt: new Date("2026-01-20"),
    declinedAt: null,
    signedAt: null,
    status: "REJECTED",
    company: companies[2]!
  },
  {
    id: 13,
    companyId: 2,
    userId: "user-1",
    position: "Principal Engineer",
    jobUrl: "https://microsoft.com/careers/13",
    jobDescription: "Principal Engineer role at Microsoft",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 250000,
    maxSalary: 400000,
    location: "Redmond, WA",
    remote: "HYBRID",
    listedAt: new Date("2025-10-01"),
    appliedAt: new Date("2025-10-15"),
    interviewAt: new Date("2025-11-15"),
    offerAt: new Date("2025-12-20"),
    rejectedAt: null,
    declinedAt: new Date("2026-01-29"),
    signedAt: null,
    status: "DECLINED",
    company: companies[1]!
  },
  {
    id: 14,
    companyId: 5,
    userId: "user-1",
    position: "Senior iOS Engineer",
    jobUrl: "https://apple.com/careers/14",
    jobDescription: "Senior iOS Engineer role at Apple",
    notes: null,
    salaryCurrency: "USD",
    minSalary: 175000,
    maxSalary: 260000,
    location: "Cupertino, CA",
    remote: "ONSITE",
    listedAt: new Date("2025-09-15"),
    appliedAt: new Date("2025-10-01"),
    interviewAt: new Date("2025-11-01"),
    offerAt: new Date("2025-12-15"),
    rejectedAt: null,
    declinedAt: null,
    signedAt: new Date("2026-01-30"),
    status: "SIGNED",
    company: companies[4]!
  }
];

export const getInitialBoardState = (): Record<ApplicationStatus, Application[]> => {
  return {
    LISTED: dummyApplications.filter((app) => app.status === "LISTED"),
    APPLIED: dummyApplications.filter((app) => app.status === "APPLIED"),
    INTERVIEW: dummyApplications.filter((app) => app.status === "INTERVIEW"),
    OFFER: dummyApplications.filter((app) => app.status === "OFFER"),
    REJECTED: dummyApplications.filter((app) => app.status === "REJECTED"),
    DECLINED: dummyApplications.filter((app) => app.status === "DECLINED"),
    SIGNED: dummyApplications.filter((app) => app.status === "SIGNED")
  };
};